name: stellarium-plars
version: 0.19
summary: Free, open source planetarium software
description: |
  Stellarium renders 3D photo-realistic skies in real-time. With Stellarium, you
  really see what you can see with your eyes, binoculars or a small telescope.
confinement: strict


apps:
  stellarium:
    command: desktop-launch $SNAP/bin/stellarium
    plugs: [unity7, opengl, network, network-bind]

parts:
  stellarium:
    plugin: cmake
    source: https://github.com/Stellarium/stellarium.git
    source-tag: v0.19
    source-depth: 1
    configflags:
      - -DCMAKE_BUILD_TYPE=Release
    build-packages:
      - build-essential
      - doxygen
      - libqt5opengl5-dev
      - libqt5serialport5-dev
      - mesa-common-dev
      - qtbase5-dev
      - qtdeclarative5-dev
      - qtdeclarative5-dev-tools
      - qtscript5-dev
      - qttools5-dev
      - qttools5-dev-tools
      - qtmultimedia5-dev
      - qtpositioning5-dev
      - zlib1g-dev
    after:
      - desktop-qt5
      - snapcraft-preload
